# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from phasespace/Cameras.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import phasespace.msg

class Cameras(genpy.Message):
  _md5sum = "c7ff3700c0cc89b1664f151f01ec9489"
  _type = "phasespace/Cameras"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """Camera[] cameras
================================================================================
MSG: phasespace/Camera
uint32 id
uint32 flags
float32 x
float32 y
float32 z
float32 qw
float32 qx
float32 qy
float32 qz
float32 cond
"""
  __slots__ = ['cameras']
  _slot_types = ['phasespace/Camera[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cameras

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Cameras, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cameras is None:
        self.cameras = []
    else:
      self.cameras = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.cameras)
      buff.write(_struct_I.pack(length))
      for val1 in self.cameras:
        _x = val1
        buff.write(_get_struct_2I8f().pack(_x.id, _x.flags, _x.x, _x.y, _x.z, _x.qw, _x.qx, _x.qy, _x.qz, _x.cond))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cameras is None:
        self.cameras = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cameras = []
      for i in range(0, length):
        val1 = phasespace.msg.Camera()
        _x = val1
        start = end
        end += 40
        (_x.id, _x.flags, _x.x, _x.y, _x.z, _x.qw, _x.qx, _x.qy, _x.qz, _x.cond,) = _get_struct_2I8f().unpack(str[start:end])
        self.cameras.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.cameras)
      buff.write(_struct_I.pack(length))
      for val1 in self.cameras:
        _x = val1
        buff.write(_get_struct_2I8f().pack(_x.id, _x.flags, _x.x, _x.y, _x.z, _x.qw, _x.qx, _x.qy, _x.qz, _x.cond))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cameras is None:
        self.cameras = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cameras = []
      for i in range(0, length):
        val1 = phasespace.msg.Camera()
        _x = val1
        start = end
        end += 40
        (_x.id, _x.flags, _x.x, _x.y, _x.z, _x.qw, _x.qx, _x.qy, _x.qz, _x.cond,) = _get_struct_2I8f().unpack(str[start:end])
        self.cameras.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I8f = None
def _get_struct_2I8f():
    global _struct_2I8f
    if _struct_2I8f is None:
        _struct_2I8f = struct.Struct("<2I8f")
    return _struct_2I8f
