base_global_planner: global_planner/Diffusion2DPlanner
# base_local_planner: dwa_local_planner/DWAPlannerROS
base_local_planner: teb_local_planner/TebLocalPlannerROS

shutdown_costmaps: false

controller_frequency: 10.0
controller_patience: 3.0

planner_frequency: 0.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

conservative_reset_dist: 0.1

recovery_behavior_enabled: false
clearing_rotation_allowed: false
