(cl:in-package unitree_legged_msgs-msg)
(cl:export '(HEAD-VAL
          HEAD
          LEVELFLAG-VAL
          LEVELFLAG
          FRAMERESERVE-VAL
          FRAMERESERVE
          SN-VAL
          SN
          VERSION-VAL
          VERSION
          BANDWIDTH-VAL
          BANDWIDTH
          IMU-VAL
          IMU
          MOTORSTATE-VAL
          MOTORSTATE
          BMS-VAL
          BMS
          FOOTFORCE-VAL
          FOOTFORCE
          FOOTFORCEEST-VAL
          FOOTFORCEEST
          TICK-VAL
          TICK
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
))